# Site settings
title: dau.
email: t.paine154@gmail.com
url: https://paine.nyc/dau
description: "dau"
baseurl: dau

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#111111'
  links: '#fff'

# Footer settings
footer: dau.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
    # url: https://twitter.com/SBootstrap
  # - title: facebook
    # url:
  # - title: stack-overflow
    # url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
    # url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/theocean154

# Build settings
markdown: kramdown
permalink: pretty
